# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- br-develop

pool:
  vmImage: ubuntu-latest

steps:

  - task: BrowserStackConfig@0
    inputs:
      BrowserStackServiceEndPoint: 'new-connection-revathy'
  - task: BrowserStackResults@1
    inputs:
      browserstackProduct: 'automate'
  - script: |
      mvn test -p parallel
    displayName: 'BrowserstackSample'
